spring:
  application:
    name: server
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lessonfour}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: mySecretKeyForJWTWhichShouldBeAtLeast256BitsLongToEnsureSecurityAndCompliance
  expiration: 86400 # 24 hours

logging:
  level:
    depromeet.lessonfour: DEBUG
    org.springframework.security: DEBUG
