spring:
  application:
    name: server
  profiles:
    group:
      pg:
        - dev
        - postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  web:
    resources:
      add-mappings: false

jwt:
  secret: mySecretKeyForJWTWhichShouldBeAtLeast256BitsLongToEnsureSecurityAndCompliance
  expiration: 86400 # 24 hours
  refresh-expiration: 604800 # days

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  file:
    name: logs/server.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 200MB
      file-name-pattern: logs/server-%d{yyyy-MM-dd}.%i.log.gz

server:
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: logs
      prefix: access
      suffix: .log
      file-date-format: .yyyy-MM-dd
      rotate: true
      pattern: common

kakao:
  client-id: ${KAKAO__CLIENT_ID:your-kakao-client-id}
  client-secret: ${KAKAO__CLIENT_SECRET:your-kakao-client-secret}
  redirect-url: ${KAKAO__REDIRECT_URL:http://localhost:8080/api/auth/kakao/callback}
  issuer-url: ${KAKAO__ISSUER_URL:https://kauth.kakao.com}
  auth-url: ${KAKAO__AUTH_URL:https://kauth.kakao.com/oauth/authorize}
  token-url: ${KAKAO__TOKEN_URL:https://kauth.kakao.com/oauth/token}

frontend:
  url: ${FRONTEND__URL:http://localhost:3000}

springdoc:
  swagger-ui:
    enabled: true   # Swagger UI 활성화
    path: /swagger-ui.html  # Swagger UI 접속 경로
    operations-sorter: method  # 메서드 기준 정렬
    tags-sorter: alpha  # 태그를 알파벳순으로 정렬
  api-docs:
    path: /v3/api-docs  # OpenAPI 문서의 기본 경로 설정
  show-actuator: true  # Actuator 관련 문서도 Swagger에서 표시

cors:
  allowed-origins: "${CORS__ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:8080,http://211.188.58.167:8080,http://211.188.58.167,https://211.188.58.167}"

app:
  server:
    url: ${APP__SERVER__URL:http://211.188.58.167}
