spring:
  application:
    name: server
  profiles:
    group:
      pg:
        - dev
        - postgres
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  file:
    name: logs/server.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 200MB
      file-name-pattern: logs/server-%d{yyyy-MM-dd}.%i.log.gz
server:
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: logs
      prefix: access
      suffix: .log
      file-date-format: .yyyy-MM-dd
      rotate: true
      pattern: common
