spring:
  application:
    name: server
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lessonfour}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: mySecretKeyForJWTWhichShouldBeAtLeast256BitsLongToEnsureSecurityAndCompliance
  expiration: 86400 # 24 hours

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  file:
    name: logs/server.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 200MB
      file-name-pattern: logs/server-%d{yyyy-MM-dd}.%i.log.gz
server:
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: logs
      prefix: access
      suffix: .log
      file-date-format: .yyyy-MM-dd
      rotate: true
      pattern: common
