spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:file:./.h2/devdb;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  server:
    url: ${APP__SERVER__URL:http://localhost:8080}

logging:
  level:
    org.flywaydb: info
