DELETE FROM food_record;
DELETE FROM activity_record;
DELETE FROM foods;
DELETE FROM users;

ALTER TABLE food_record ALTER COLUMN id RESTART WITH 1;
ALTER TABLE activity_record ALTER COLUMN id RESTART WITH 1;
ALTER TABLE foods ALTER COLUMN id RESTART WITH 1;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
